### PR TITLE
TT-916 Update TOML keys with secrets for E2E tests

### PR DESCRIPTION
**Pull request by lukaszcl**
## Motivation
This adds `_secret` suffix to some TOML keys for E2E tests. 

## Solution
This is to make the TOML configs compatible with next CTF version https://github.com/smartcontractkit/chainlink-testing-framework/pull/835

## TODO
- [x] Confirm with @AnieeG
- [x] Remove [a08d3e0](https://github.com/smartcontractkit/ccip/pull/524/commits/a08d3e0c1a24bf6527efe4a85d3ac2cecc93e2ea) commit before merge

### CODE REVIEW

**Review by AnieeG — COMMENTED** [review]
You need to update the toml files accordingly within 
https://github.com/smartcontractkit/ccip/blob/ccip-develop/integration-tests/ccip-tests/testconfig/tomls/sample-secrets.toml
and the readme - https://github.com/smartcontractkit/ccip/blob/ccip-develop/integration-tests/ccip-tests/README.md

**Comment by lukaszcl** [comment]
I discussed with Ani that that this PR should be green before we can merge https://github.com/smartcontractkit/chainlink-testing-framework/pull/835 cc @AnieeG

**Comment by AnieeG** [comment]
> I discussed with Ani that that this PR should be green before we can merge [smartcontractkit/chainlink-testing-framework#835](https://github.com/smartcontractkit/chainlink-testing-framework/pull/835) cc @AnieeG

Looks green :)

**Comment by lukaszcl** [comment]
@AnieeG this is now ready to merge!

**Comment by lukaszcl** [comment]
@AnieeG it's fails on something. Let me check later today and let you know

**Comment by lukaszcl** [comment]
@AnieeG this should be now ready to review and merge!

**Review by AnieeG — APPROVED** [review]

**Pull request merged**
